rootProject.name = "potatocloud"
include("api")
include("connector")
include("node")
include("core")
include("plugin-limbo")
include("plugin-spigot")
include("plugin-velocity")
include("plugins")
include("plugins:cloudcommand")
include("plugins:hub")
include("plugins:labymod")
include("plugins:notify")
include("plugins:proxy")