# PotatoCloud WebInterface Module

port: 8080
# Use 127.0.0.1 to expose only locally, 0.0.0.0 for network access (not recommended for production without proper security measures!)
bind-address: "127.0.0.1"
# The JWT secret is used for the websocket validation
jwt-secret: "a-very-long-secret-key-with-a-minimum-of-32-characters"

# If you disable this, the websocket and REST api can be accessed WITHOUT any authentication! This is NOT recommended for production environments.
require-auth: true
# These api keys are used for the REST api (They are not used for the websocket authentication, which relies solely on the JWT token)
api-keys:
  - "change-me-7f4c8b2a1e9d3c0b"

ws-ping-interval-seconds: 30
ws-update-interval-seconds: 5